### ISSUE TITLE
升级到2.0后 replaceAll 会自动滚动到最后一个Item

### ISSUE THREAD

**Issue by MAIMIHO** [qyxxjd/CommonAdapter#10]
2.0 replaceAll(@NonNull List<T> item)方法变更后会自动滚动到最后一个Item, 
需要使用replaceAll(items, false) 
mAdapter.notifyDataSetChanged();
才会保持在当前位置. 
2.0里面的改动有什么好处吗?

**Comment by qyxxjd** [comment]
> RecyclerView and java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder in Samsung devices

[https://stackoverflow.com/questions/31759171/recyclerview-and-java-lang-indexoutofboundsexception-inconsistency-detected-in](https://stackoverflow.com/questions/31759171/recyclerview-and-java-lang-indexoutofboundsexception-inconsistency-detected-in)
