### ISSUE TITLE
每次要加载图片都要setImageLoad一下不是那么nice啊

### ISSUE THREAD

**Issue by xuhuan** [qyxxjd/CommonAdapter#3]
目前方式如下:
```
//加载网络图片之前，请调用setImageLoad方法，设置网络图片加载的实现类
helper.setImageLoad(new GlideImageLoad());
helper.setImageUrl(R.id.xxx,url);
```

用是可以用,但是每次都要配置一次挺烦的,一般一个项目里就用一个图片加载类,没必要每个都设置一次吧,有没有更好的方式呢?哪怕初始化的时候设置一次也可以接受啊.或者提供适配不同图片加载类库的jar也可以,这样子就不用自己配置了.

**Comment by qyxxjd** [comment]
感谢你的反馈!下个版本改善这个问题。

**Comment by qyxxjd** [comment]
`v1.4`版本已发布：
* 新增全局图片加载配置
* `CommonRecyclerAdapter`优化

详见`demo`或`readme`
