### ISSUE TITLE
CommonRecyclerAdapter 调用notifyDataSetChanged不起作用

### ISSUE THREAD

**Issue by liuxing1992** [qyxxjd/CommonAdapter#4]
我的布局是一个RecyclerView 里面有刷新和加载更多 每次刷新或加载完后要刷新都用notifyDataSetChanged 但没反应

**Comment by qyxxjd** [comment]
调用`CommonRecyclerAdapter`以下API试试：
`addAll(List<T> elem)`  加载更多时新增数据通过这个方法添加
`replaceAll(List<T> elem)` 下拉刷新时数据全部更新，调用这个方法，最新的`v1.4`已结废弃这个方法，建议使用下面这个官方推荐的方法
`replaceAll(List<T> elem, DiffUtil.Callback callback)` 稍后空了我写个示例到`demo`

**Comment by liuxing1992** [comment]
按照你给的方法 已经弄好了 谢谢🙏
