### ISSUE TITLE
当RecyclerView有头部的时候 用DiffUtil刷新会刷新错位置 有时还会异常退出

### ISSUE THREAD

**Issue by liuxing1992** [qyxxjd/CommonAdapter#5]

**Comment by qyxxjd** [comment]
感谢你的反馈，我测试一下

**Comment by qyxxjd** [comment]
我更新了`Demo`，添加了使用`DiffUtil`的示例，你对比再试试
[RecyclerViewActivity](https://github.com/qyxxjd/CommonAdapter/blob/master/app/src/main/java/com/classic/adapter/simple/activity/RecyclerViewActivity.java)
[RecyclerViewSimpleActivity](https://github.com/qyxxjd/CommonAdapter/blob/master/app/src/main/java/com/classic/adapter/simple/activity/RecyclerViewSimpleActivity.java)
