### ISSUE TITLE
Item子项点击

### ISSUE THREAD

**Issue by Reginer** [qyxxjd/CommonAdapter#6]
不知道可不可以在库里面加个item库的子项点击事件，仔细看了下这个库，感觉可以这样添加。针对RecyclerView库的。
在CommonRecyclerAdapter里加上如下代码：

private OnItemChildClickListener onItemChildClickListener;
private OnItemLongChildClickListener onItemLongChildClickListener;

public void setOnItemChildClickListener(OnItemChildClickListener onItemChildClickListener) {
        this.onItemChildClickListener = onItemChildClickListener;
    }

    public void setOnItemLongChildClickListener(OnItemLongChildClickListener onItemLongChildClickListener) {
        this.onItemLongChildClickListener = onItemLongChildClickListener;
    }

protected void setOnItemChildClickListener(BaseAdapterHelper helper, final int position, Integer... param) {
        if (onItemChildClickListener != null) {
            for (Integer aParam : param) {
                helper.getView(aParam).setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View view) {
                        onItemChildClickListener.onChildClick(view, position);
                    }
                });
            }
        }
    }

    protected boolean setOnItemLongChildClickListener(BaseAdapterHelper helper, final int position, Integer... param) {
        if (onItemLongChildClickListener != null) {
            for (Integer aParam : param) {
                helper.getView(aParam).setOnLongClickListener(new View.OnLongClickListener() {
                    @Override
                    public boolean onLongClick(View view) {
                        return onItemLongChildClickListener.onLongChildClick(view, position);
                    }
                });
            }
        }
        return false;
    }

public interface OnItemChildClickListener {
        void onChildClick(View v, int position);
    }

    public interface OnItemLongChildClickListener {
        boolean onLongChildClick(View v, int position);
    }

就可以这样在Adapter里为子项加上监听了：
setOnItemChildClickListener(helper,position,R.id.child1,R.id.child2);

在Activity里就可以这样写了:
mAdapter.setOnItemChildClickListener(this);

仅仅是点建议。

**Comment by qyxxjd** [comment]
感谢您的建议，忙完这几天我看下，谢谢！

**Comment by qyxxjd** [comment]
`BaseAdapterHelper` 已内置常用的点击事件
``` java
helper.setText(R.id.viewId, text)
      .setTag(R.id.viewId, objectTag)
      .setAlpha(R.id.viewId, 0.6f)
      .setBackgroundColor(R.id.viewId, R.color.colorResId)
      .setBackgroundRes(R.id.viewId, R.drawable.drawableResId)
      .setChecked(R.id.viewId, true)
      .setImageBitmap(R.id.viewId, bitmap)
      .setImageDrawable(R.id.viewId, drawable)
      .setImageResource(R.id.viewId, R.drawable.drawableResId)
      .setImageUrl(R.id.viewId, url)
      .setProgress(R.id.viewId, progress)
      .setProgress(R.id.viewId, progress, max)
      .setRating(R.id.viewId, rating)
      .setRating(R.id.viewId, rating, max)
      .setTextColor(R.id.viewId, R.color.colorResId)
      .setTextColorRes(R.id.viewId, R.color.colorResId)
      .setTextColorRes(R.id.viewId, R.color.colorResId, theme)
      //TextView添加超链接，更多属性参考：android.text.util.Linkify#addLinks(TextView text, int mask)
      .addLinks(R.id.viewId, Linkify.ALL)
      //效果同上
      .addAllLinks(R.id.viewId)
      //单个TextView设置Typeface
      .setTypeface(R.id.viewId, typeface)
      //多个TextView设置Typeface
      .setTypeface(typeface, R.id.xxx1, R.id.xxx2, R.id.xxx3, ...)
      .setVisible(R.id.viewId, View.VISIBLE)
      //ProgressBar设置Max
      .setMax(R.id.viewId, max)
      //ListView设置adapter
      .setAdapter(R.id.viewId, adapter)
      //下面为View常用点击事件设置
      .setOnTouchListener(R.id.viewId, onTouchListener)
      .setOnClickListener(R.id.viewId, onClickListener)
      .setOnLongClickListener(R.id.viewId, onLongClickListener)
      .setOnItemClickListener(R.id.viewId, onItemClickListener)
      .setOnItemLongClickListener(R.id.viewId, onItemLongClickListener)
      .setOnItemSelectedClickListener(R.id.viewId, onItemSelectedListener);
```

**Comment by Reginer** [comment]
恕在下愚钝，你这样写点击事件，子项的点击事件，不就处理在了adapter里了 ？

**Comment by qyxxjd** [comment]
@Reginer [CommonAdapter 1.8.1](https://github.com/qyxxjd/CommonAdapter/releases)
