### ISSUE TITLE
如果想要在Adapter里使用DataBinding怎么办呢？

### ISSUE THREAD

**Issue by Lsy1992** [qyxxjd/CommonAdapter#7]
例如: 
   ListBinding binding = DataBindingUtil.bind(convertView);
   binding.setData(item);

**Comment by qyxxjd** [comment]
由于 `DataBinding` 没有在正式项目中使用过，个人对 `DataBinding` 也没有过多的了解，暂时还不支持 `DataBinding`

**Comment by Lsy1992** [comment]
就是说有没有方法能返回convertView的？

**Comment by qyxxjd** [comment]
```java
    @Override public void onUpdate(BaseAdapterHelper helper, News item, int position) {
        //获取item的convertView
        View convertView = helper.getView();
    }
```

**Comment by Lsy1992** [comment]
三克油

**Comment by 529523346** [comment]
@Lsy1992 请问你是只卖实现绑定的？我用DataBindingUtil.bind(helper.getView());貌似不行，就大神科普
